# Generated by Django 6.0.6 on 2026-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='property_status',
            field=models.CharField(choices=[('for_sale', 'در حال فروش'), ('sold', 'فروخته شده')], default='for_sale', max_length=20),
        ),
    ]
