# Generated by Django 6.0.6 on 2026-07-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='property_status',
        ),
    ]
