# Generated by Django 6.0.6 on 2026-06-22 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('properties', '0002_propertyimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('mortgage', 'Mortgage')], max_length=20)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customers.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='properties.property')),
            ],
        ),
    ]
