# Generated by Django 6.0.6 on 2026-06-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('land', 'Land'), ('office', 'Office'), ('shop', 'Shop')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('pre_sale', 'Pre Sale'), ('mortgage', 'Mortgage')], max_length=20)),
                ('price', models.BigIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
