# Generated by Django 6.0.6 on 2026-06-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('properties', '0003_propertyimage_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='agency',
        ),
        migrations.AddField(
            model_name='property',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agencies.agency'),
        ),
    ]
