# Generated by Django 6.0.6 on 2026-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
