# Generated by Django 6.0.6 on 2026-07-11 17:57

import properties.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertyimage_is_cover_propertyimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/', validators=[properties.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(upload_to='properties/videos/', validators=[properties.validators.validate_video]),
        ),
    ]
