# Generated by Django 6.0.6 on 2026-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('properties', '0010_remove_property_is_favorite_propertyfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('agency', 'code')},
        ),
    ]
