# Generated by Django 6.0.6 on 2026-08-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_code_alter_property_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.BigIntegerField(blank=True, help_text='پیش\u200cپرداخت (ودیعه) — فقط برای ملک\u200cهای اجاره\u200cای.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rent',
            field=models.BigIntegerField(blank=True, help_text='اجاره ماهانه — فقط برای ملک\u200cهای اجاره\u200cای.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.BigIntegerField(blank=True, help_text='برای معاملات فروش و رهن الزامی است.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('land', 'Land'), ('office', 'Office'), ('shop', 'Shop'), ('suite', 'Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('mortgage', 'Mortgage')], max_length=20),
        ),
    ]
