# Generated by Django 6.0.6 on 2026-07-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
