# Generated by Django 6.0.6 on 2026-07-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('customers', '0003_customer_phone_2_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('agency', 'phone')},
        ),
    ]
