# Generated by Django 6.0.6 on 2026-06-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('properties', '0002_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agencies.agency'),
        ),
    ]
