# Generated by Django 6.0.6 on 2026-06-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_elevator_property_floor_property_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
